language: node_js
node_js:
  - 'node'
cache: npm
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: dist
  on:
    branch: master
